[colors.primary]
background = "#1A1B26"
foreground = "#A9B1D6"
dim_foreground = "#A9B1D6"
bright_foreground = "#A9B1D6"

[colors.cursor]
text = "#1A1B26"
cursor = "#9AA5CE"

[colors.vi_mode_cursor]
text = "#1A1B26"
cursor = "#7AA2F7"

[colors.search.matches]
foreground = "#1A1B26"
background = "#3B4261"

[colors.search.focused_match]
foreground = "#1A1B26"
background = "#9ECE6A"

[colors.footer_bar]
foreground = "#1A1B26"
background = "#3B4261"

[colors.hints.start]
foreground = "#1A1B26"
background = "#E0AF68"

[colors.hints.end]
foreground = "#1A1B26"
background = "#3B4261"

[colors.selection]
text = "#1A1B26"
background = "#565F89"

[colors.normal]
black = "#15161E"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#A9B1D6"

[colors.bright]
black = "#32344A"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#C0CAF5"

[colors.dim]
black = "#15161E"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#A9B1D6"

[[colors.indexed_colors]]
index = 16
color = "#FF9E64"

[[colors.indexed_colors]]
index = 17
color = "#DB4B4B"
